### ISSUE TITLE
Es ist unmöglich eine Funktion mit dem Rückgabetyp Zeichen Array zu erstellen.

### ISSUE THREAD

**Issue by NotLe0n** [NotLe0n/Die-Deutsche-Programmiersprache#2]
## Problem

Eigendlich sollte es so aussehen:
```
die Funktion foo() vom Typ Zeichen macht:
      [...]
```

Da aber das wort Zeichen kein Plural hat würde die obrige Funktion den Typ Zeichen (singular) haben.

Die Differenzierung zwischen singular und plural geht nur mit einem Artikel, welches bei dem Syntax einer Funktionsdeklaration weggelassen wird.

## Mögliche Lösungen

1. Man könnte einfach Zeichen ein 's' hinten anhängen. Das wäre zwar nicht grammatikalisch korrekt, würde aber das Problem ganz einfach lösen
2. Statt dem Wort Zeichen/Zeichen, Charakter/Charaktere benutzen
3. Funktionsdeklarationssyntax ändern

**Comment by bafto** [comment]
Die 2. Lösung wäre wohl vorzuziehen.
Vorschlag: Buchstabe/Buchstaben statt Charakter/Charaktere, da Charakter auf Deutsch nicht dem englischen "character" entspricht, sondern eine Persönlichkeit bezeichnet.

**Comment by NotLe0n** [comment]
mit a18cc00 geschlossen
