### ISSUE TITLE
Strukturen

### ISSUE THREAD

**Issue by NotLe0n** [NotLe0n/Die-Deutsche-Programmiersprache#5]
Strukturen sind so wie Klassen in anderen Programmiersprachen. Strukturen können Variablen und Funktion beinhalten und von anderen Strukturen vererben.

## Deklarations-Syntax
```
die Struktur Schüler beschreibt:
  die Zahl Alter.
  der Text Name.
  der Text Haarfarbe.
  der Boolean faul ist wahr.
  der Boolean schläft.

  die Funktion Schlafen() macht:
    schläft ist wahr.
````

## Vererbung
```
die Struktur Schüler vererbt von Mensch und beschreibt:
  ...
````

## Instanz erstellen
```
Schüler schüler ist ein neuer Schüler().
```

## Eigenschaftszugriff
```
Schüler schüler ist ein neuer Schüler().
die Eigenschaft Alter von schüler ist 18.
```

**Comment by bafto** [comment]
why tho?

**Comment by NotLe0n** [comment]
> why tho?

weil OOP ein Teil jeder großen Programmiersprache ist und wir es relativ einfach implementieren können, da wir schon eine Vorlage in "crafting-interpeters" haben. Der einzige Grund warum wir es noch nicht implementiert hatten war, dass wir uns nicht auf ein Wort für class einigen könnten.

**Comment by bafto** [comment]
Strukturen (wie structs in c oder Go) sind nützlich, aber ich denke nicht, dass wir Methoden, oder gar Vererbung brauchen.
Es reichen simple Strukturen die du mit Funktionene manipulieren kannst, à la:
```
die Struktur Schüler beschreibt:
    die Zahl alter.
    den Text name.
    der Boolean schläft.

die Funktion schlafe(Schüler s) vom Typ Schüler macht:
    s.schläft ist wahr. //punk syntax nur für das Beispiel.
    gib s zurück.
```
Das ist natürlicher etwas aufwendiger, aber kein Problem für jemanden der irgendwann mal etwas anderes als c# programmiert hat (ja das ist ein front!! jjk) oder jemanden der gerade erst lernt zu programmieren und es nicht anders kennt (es wird eh kein Anfänger DDP programmieren und wenn doch dann lernt er halt weniger OOP, das braucht man eh nicht zwingend).
Richtiges OOP zu implementieren fände ich deutlich übertrieben für DDP, da es hauptsächlich um die deutsche Syntax geht, und wir diese am besten mit so wenigen Features wie möglich erhalten können (Methoden Deklarationen deutsch klingen zu lassen wäre seeehr schwer denke ich), allein schon "die Eigenschaft Alter von schüler..." klingt komisch, da brauchen wir nicht noch Vererbung oder Methoden.

**Comment by NotLe0n** [comment]
>Strukturen (wie structs in c oder Go) sind nützlich, aber ich denke nicht, dass wir Methoden, oder gar Vererbung brauchen.

Ich wäre einverstanden Methoden auszulassen, sodass der Syntax nicht zu komisch klingt.

> Richtiges OOP zu implementieren fände ich deutlich übertrieben für DDP, da es hauptsächlich um die deutsche Syntax geht, und wir diese am besten mit so wenigen Features wie möglich erhalten können (Methoden Deklarationen deutsch klingen zu lassen wäre seeehr schwer denke ich), allein schon "die Eigenschaft Alter von schüler..." klingt komisch, da brauchen wir nicht noch Vererbung oder Methoden.

DDP braucht **kein** volles OOP _(Datenkapselung, Persistenz, Polymorphie, Abstraktion)_, aber ich will wenigstens Vererbung behalten, da Vererbung komplexere Systeme ermöglicht und einer der wichtigsten Bestandteile von OOP beibringt. Man weiß ja nie ob diese Sprache mal ernst benutzt wird (ich bezweifle es trotzdem). Über `"die Eigenschaft x von y."` kann man noch Diskutieren. Ich finde, dass es trotz der Länge nicht so schlimm klingt.

**Comment by bafto** [comment]
Syntax Vorschlag:
```
die Struktur Test beschreib:
    Zahl x ist 420, //der Nutzer muss für jeden Member einen Standard Wert definieren
    Text t ist "Hallo" //wenn kein Komma mehr kommt ist die Strukturdeklaration fertig

die Test Struktur t ist Test{x: 666; t: "Hallo"}. //Member können mit ihrem Namen initialisiert werden
die Test Struktur t2 ist Test{}. //oder alles kann beim Standard Wert gelassen werden
die Test Struktur t3 ist Test{x: 7}. //man kann auch nur einzelne Member initialisieren und der Rest bleibt beim Standard Wert
die Test Strukturen ts sind [Test{}; Test{x: 7}; Test{t: "hi"; x: 69}].

//es muss immer Struktur/Strukturen dazu geschrieben werden (liest sich auch gut)
die Funktion foo(Test Struktur t) vom Typ Test Strukturen macht:
    gib [t; Test{}] zurück.
```
Vorschlag für Member Zugriff:
```
die Struktur Test beschreib:
    Zahl x ist 420,
    Text t ist "Hallo"

die Test Struktur t ist Test{}.
t->x ist 5.
die Zahl y ist t->x.
```
Pfeil statt Punkt Syntax falls wir keine Worte benutzen wollen.
Vorteil: es ist kurz und verlängert nichts unnötig und gerät nicht in Konflikt mit dem Punkt der eine Zeile beendet.
Nachteil: liest sich nicht sehr Deutsch.

**Comment by NotLe0n** [comment]
Mir gefällt der Syntax soweit, aber ich bin kein fan von dem Pfeil (->) syntax. In dieser Programmiersprache müssen wir weniger Zeichen und mehr Wörter benutzen. Es ist schon schade, dass der Funktionssyntax klammern benutzt aber, das können wir wahrscheinlich nicht ändern.

Ein paar Vorschläge:
###### x => Eigenschaftsname
###### y => Strukturname

1. `die Eigenschaft x von y.`
2. `Eigenschaft x von y.`
3. `x von y.`
